name: C++11 Build (macOS Intel)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-macos-intel:
    runs-on: macos-13  # macOS Ventura (last version with Intel support)
    env:
      MACOSX_DEPLOYMENT_TARGET: "10.15"  # Optional: Set min macOS version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build for Intel (x86_64)
        run: |
          # Explicitly compile for x86_64
          make CXX="clang++ -target x86_64-apple-macos10.15"

      - name: Upload Intel binary
        uses: actions/upload-artifact@v4
        with:
          name: vps_srv-macos-intel
          path: vps_srv